"use client";
import { ParallaxScroll } from "./ui/parallax-scroll";

 function GallerySection() {
  return (
    <div className="z-[6]">
      <ParallaxScroll images={images} />
    </div>
  );
}

const images = [
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
      "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
  "/toshita1.jpg",
  "/toshita.jpg",
];

export default GallerySection;
